; Script generated by Inno Setup Script Wizard.
; Bulk Crap Uninstaller (BCU) Setup Script

#define MyAppName "Bulk Crap Uninstaller"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "Italo Almeida"
#define MyAppURL "https://github.com/italoalmeida0/bcu"
#define MyAppExeName "bcu.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{D3A15C22-1B67-4632-901B-E7E50949AE8C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\BCU
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
OutputDir=..\dist
OutputBaseFilename=bcu-v{#MyAppVersion}-windows-x86_64-installer
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "addtopath"; Description: "Add BCU to user PATH (recommended to run 'bcu' in terminal)"; GroupDescription: "System Integration:"

[Files]
Source: "..\dist\arm64\bcu.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\LICENSE"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName} TUI"; Filename: "{app}\{#MyAppExeName}"; Parameters: "tui"
Name: "{autoprograms}\{#MyAppName} Uninstall"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName} TUI"; Filename: "{app}\{#MyAppExeName}"; Parameters: "tui"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Tasks: addtopath; Check: NeedsAddPath(ExpandConstant('{app}'))

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  { Look for the path with leading and trailing semicolons }
  { To simple search: }
  Result := Pos(';' + UpperCase(Param) + ';', ';' + UpperCase(OrigPath) + ';') = 0;
end;

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "tui"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')} TUI}"; Flags: nowait postinstall skipifsilent
